### PR TITLE
GUI: Initialise class and struct members in the headers

### PR DESCRIPTION
**Pull request by michaelpm54**

### CODE REVIEW

**Comment by DrMcCoy** [comment]
Nice, merged, thanks! :)

**Comment by farmboy0** [comment]
Is it really a good idea to do this in the headers and in the constructor?

**Comment by DrMcCoy** [comment]
Yeah, that's the C++11 way. The advantage is that you're not going to forget to initialize some members in a second contructor, for example.

**Comment by DrMcCoy** [comment]
And yes, forgetting to initialize a member in an alternate constructor happens a lot in xoreos. Might be one of more frequent mistakes Coverity Scan complains about.

So I'm quite happy to have another tool in the toolbox for removing that error case. :)

Also, and that might be just me, I prefer having the default value right with member definition in the class. Makes it more obvious what the default is, as opposed to having to hunt for it in a constructor (and then having to check if that differs in different constructors, if the class has them).

And makes it obvious that, yes, we do initialize that pointer always, it can't be invalid. Of course, I also like to get away from using raw pointers as much as possible, instead using, well, ScopedPtr in pre-C++11 xoreos and std::unique_ptr for the GUI in Phaethon (and potentially in the future for xoreos, too, since I'd like to upgrade xoreos to C++11 some day).

**Pull request merged**
