### PR TITLE
GUI: Add key shortcuts

### PR DESCRIPTION
**Pull request by michaelpm54**

### CODE REVIEW

**Comment by DrMcCoy** [comment]
Hmm, it doesn't display the Ctrl+Q in the menu, though.

Other keyboard shortcuts the wxWidgets Phaethon had:
- Ctrl+D: open directory
- Ctrl+W: close
- F1: about

Also, the Qt Phaethon currently has "&Open directory" and "&Open file". I guess the underline should go somewhere else on one of them. "Quit" could be "&Quit", "About" could be "&About".

**Comment by DrMcCoy** [comment]
Huh, why did you remove underline on all of them now? I'd like to keep that, but they need to be on different letters each, so that they can be activated with Alt + that letter. All menu item should ideally have them, in addition to usual shortcuts.

(Well, reusing the same letter in a sub-menu is probably okay. I.e. "&File" could probably have "Open &file" without that clashing, but the Help menu shouldn't have anything on F.)

**Comment by michaelpm54** [comment]
Updated with the underline shortcuts back.

**Comment by DrMcCoy** [comment]
Merged, thanks! :)

**Pull request merged**
